language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y unoconv
  
install:
  - pip install coverage
  - pip install .

script:
  - coverage run ./tests/test_converter.py