language: python

python:
  - "2.7"
  - "3.4"
  
notifications:
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y unoconv
  
install:
  - pip install codecov
  - pip install uno
  - pip install .

script:
  - coverage run ./tests/test_converter.py

after_script:
  - codecov
